"""
Evaluate Models — Évaluation offline des modèles ML.
Métriques: AUC-ROC, Recall@10, NDCG@10, Precision@5.

Usage:
  python -m scripts.evaluate_models --model two_tower --split test
  python -m scripts.evaluate_models --model all --output_csv eval_results.csv
"""

from __future__ import annotations
import argparse
import csv
import logging
import os
import time
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def compute_auc_roc(y_true: np.ndarray, y_scores: np.ndarray) -> float:
    """AUC-ROC via sklearn."""
    try:
        from sklearn.metrics import roc_auc_score
        return float(roc_auc_score(y_true, y_scores))
    except Exception as e:
        logger.error(f"AUC-ROC failed: {e}")
        return 0.0


def compute_recall_at_k(ranked_lists: list[list[str]], relevant_items: list[set], k: int = 10) -> float:
    """Recall@K moyen sur toutes les requêtes."""
    recalls = []
    for ranked, relevant in zip(ranked_lists, relevant_items):
        if not relevant:
            continue
        hits = sum(1 for item in ranked[:k] if item in relevant)
        recalls.append(hits / len(relevant))
    return float(np.mean(recalls)) if recalls else 0.0


def compute_ndcg_at_k(ranked_lists: list[list[str]], relevant_items: list[set], k: int = 10) -> float:
    """NDCG@K moyen."""
    def dcg(items, relevant, k):
        return sum(
            (1.0 / np.log2(i + 2)) if items[i] in relevant else 0.0
            for i in range(min(k, len(items)))
        )

    def idcg(relevant, k):
        return sum(1.0 / np.log2(i + 2) for i in range(min(k, len(relevant))))

    ndcgs = []
    for ranked, relevant in zip(ranked_lists, relevant_items):
        if not relevant:
            continue
        dcg_val = dcg(ranked, relevant, k)
        idcg_val = idcg(relevant, k)
        ndcgs.append(dcg_val / idcg_val if idcg_val > 0 else 0.0)
    return float(np.mean(ndcgs)) if ndcgs else 0.0


def compute_precision_at_k(ranked_lists: list[list[str]], relevant_items: list[set], k: int = 5) -> float:
    """Precision@K moyen."""
    precisions = []
    for ranked, relevant in zip(ranked_lists, relevant_items):
        hits = sum(1 for item in ranked[:k] if item in relevant)
        precisions.append(hits / k)
    return float(np.mean(precisions)) if precisions else 0.0


def evaluate_model(
    model_name: str,
    split: str = "test",
) -> dict[str, float]:
    """Évalue un modèle sur le split de test et retourne les métriques."""
    logger.info(f"Evaluating {model_name} on {split} split...")
    t = time.time()

    metrics = {
        "model": model_name,
        "split": split,
        "auc_roc": 0.0,
        "recall_at_10": 0.0,
        "ndcg_at_10": 0.0,
        "precision_at_5": 0.0,
        "latency_ms": 0.0,
    }

    try:
        from ml.serving.registry import ModelRegistry
        registry = ModelRegistry()

        # Load real test data from the training pipeline
        logger.info(f"  Loading {split} samples for {model_name}...")

        # Load test data from the checkpoint directory (generated by train.py)
        import json
        from pathlib import Path

        test_data_path = Path(f"checkpoints/{model_name}/test_predictions.json")
        if test_data_path.exists():
            with open(test_data_path) as f:
                test_results = json.load(f)
            y_true = np.array(test_results["labels"])
            y_scores = np.array(test_results["predictions"])
        else:
            # Generate predictions from real model on test split
            logger.info(f"  No cached predictions — running inference on {split} set...")
            test_samples_path = Path(f"data/{split}_events.parquet")
            if not test_samples_path.exists():
                logger.error(
                    f"  No test data at {test_samples_path}. "
                    f"Run training first: python -m ml.training.train --model {model_name}"
                )
                return metrics

            import pandas as pd
            df = pd.read_parquet(test_samples_path)
            y_true = df["label"].values if "label" in df.columns else df["label_click"].values
            y_scores = registry.predict_batch(model_name, df)

        metrics["auc_roc"] = compute_auc_roc(y_true, y_scores)

        # Retrieval metrics — use real user histories from test split
        if model_name in ("two_tower", "din", "dien", "bst"):
            ranked_lists_path = Path(f"checkpoints/{model_name}/test_rankings.json")
            if ranked_lists_path.exists():
                with open(ranked_lists_path) as f:
                    rankings_data = json.load(f)
                ranked_lists = rankings_data["ranked"]
                relevant_items = [set(r) for r in rankings_data["relevant"]]
            else:
                logger.warning(f"  No ranking data at {ranked_lists_path} — retrieval metrics skipped")
                ranked_lists = []
                relevant_items = []

            if ranked_lists:
                metrics["recall_at_10"] = compute_recall_at_k(ranked_lists, relevant_items, k=10)
                metrics["ndcg_at_10"] = compute_ndcg_at_k(ranked_lists, relevant_items, k=10)
                metrics["precision_at_5"] = compute_precision_at_k(ranked_lists, relevant_items, k=5)

        metrics["latency_ms"] = (time.time() - t) * 1000

    except Exception as e:
        logger.error(f"Evaluation failed for {model_name}: {e}")

    logger.info(
        f"  {model_name}: AUC={metrics['auc_roc']:.4f} "
        f"R@10={metrics['recall_at_10']:.4f} "
        f"NDCG@10={metrics['ndcg_at_10']:.4f} "
        f"P@5={metrics['precision_at_5']:.4f} "
        f"({metrics['latency_ms']:.1f}ms)"
    )
    return metrics


# ── Post-Training Visualization ────────────────────────────────

def generate_plots(all_metrics: list[dict], output_dir: str = "checkpoints") -> None:
    """Generate post-training visualizations.

    Plots:
        1. Learning curves (train_loss vs val_loss per epoch)
        2. Model comparison (AUC/NDCG bar chart)
        3. ROC curves (if y_true/y_scores available)
    """
    try:
        import matplotlib
        matplotlib.use("Agg")  # Non-interactive backend for servers
        import matplotlib.pyplot as plt
    except ImportError:
        logger.warning("matplotlib not installed — skipping plots. pip install matplotlib")
        return

    from pathlib import Path

    plots_dir = Path(output_dir) / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)

    # ── 1. Learning Curves ─────────────────────────────────────
    for m in all_metrics:
        model_name = m["model"]
        history_path = Path(output_dir) / model_name / "training_history.json"
        if not history_path.exists():
            continue

        import json as _json
        with open(history_path) as f:
            history = _json.load(f)

        if not history.get("epochs"):
            continue

        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        # Loss curves
        axes[0].plot(history["epochs"], history["train_loss"], "b-", linewidth=2, label="Train Loss")
        axes[0].plot(history["epochs"], history["val_loss"], "r-", linewidth=2, label="Val Loss")
        axes[0].set_xlabel("Epoch")
        axes[0].set_ylabel("Loss")
        axes[0].set_title(f"{model_name} — Learning Curves")
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        # AUC curves (if available)
        auc_keys = [k for k in history if k.startswith("auc_")]
        if auc_keys:
            for k in auc_keys:
                axes[1].plot(history["epochs"], history[k], linewidth=2, label=k)
            axes[1].set_xlabel("Epoch")
            axes[1].set_ylabel("AUC")
            axes[1].set_title(f"{model_name} — AUC per Task")
            axes[1].legend()
            axes[1].grid(True, alpha=0.3)
        else:
            axes[1].text(0.5, 0.5, "No AUC data", ha="center", va="center")
            axes[1].set_title(f"{model_name} — No AUC Data")

        plt.tight_layout()
        path = plots_dir / f"learning_curves_{model_name}.png"
        fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        logger.info(f"  Plot saved: {path}")

    # ── 2. Model Comparison ────────────────────────────────────
    models_with_auc = [m for m in all_metrics if m.get("auc_roc", 0) > 0]
    if models_with_auc:
        fig, axes = plt.subplots(1, 2, figsize=(14, 6))

        names = [m["model"] for m in models_with_auc]
        aucs = [m["auc_roc"] for m in models_with_auc]
        ndcgs = [m.get("ndcg_at_10", 0) for m in models_with_auc]

        # AUC comparison
        bars = axes[0].barh(names, aucs, color="steelblue", alpha=0.8)
        axes[0].set_xlabel("AUC-ROC")
        axes[0].set_title("Model Comparison — AUC-ROC")
        axes[0].set_xlim(0, 1)
        axes[0].grid(True, alpha=0.3, axis="x")
        for bar, val in zip(bars, aucs):
            axes[0].text(bar.get_width() + 0.01, bar.get_y() + bar.get_height() / 2,
                         f"{val:.4f}", va="center", fontsize=10)

        # NDCG comparison
        bars = axes[1].barh(names, ndcgs, color="coral", alpha=0.8)
        axes[1].set_xlabel("NDCG@10")
        axes[1].set_title("Model Comparison — NDCG@10")
        axes[1].set_xlim(0, 1)
        axes[1].grid(True, alpha=0.3, axis="x")
        for bar, val in zip(bars, ndcgs):
            axes[1].text(bar.get_width() + 0.01, bar.get_y() + bar.get_height() / 2,
                         f"{val:.4f}", va="center", fontsize=10)

        plt.tight_layout()
        path = plots_dir / "model_comparison.png"
        fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        logger.info(f"  Plot saved: {path}")

    logger.info(f"All plots saved to: {plots_dir}")


def main():
    parser = argparse.ArgumentParser(description="Offline model evaluation")
    parser.add_argument("--model", default="all",
                        choices=["two_tower", "mtl_ple", "din", "dien", "bst", "deepfm", "all"])
    parser.add_argument("--split", default="test", choices=["val", "test"])
    parser.add_argument("--output_csv", default="eval_results.csv")
    parser.add_argument("--no-plots", action="store_true", help="Skip plot generation")
    args = parser.parse_args()

    models = (
        ["two_tower", "mtl_ple", "din", "dien", "bst", "deepfm"]
        if args.model == "all"
        else [args.model]
    )

    all_metrics = [evaluate_model(m, args.split) for m in models]

    # Export CSV
    if all_metrics:
        with open(args.output_csv, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=all_metrics[0].keys())
            writer.writeheader()
            writer.writerows(all_metrics)
        logger.info(f"Results saved to {args.output_csv}")

    # Generate plots
    if not args.no_plots and all_metrics:
        logger.info("Generating post-training visualizations...")
        generate_plots(all_metrics)


if __name__ == "__main__":
    main()

